import type { Agent } from './types';

export const initialAgents: Agent[] = [
  {
    id: 'gengis',
    name: 'Gengis Khan',
    role: 'CEO',
    color: '#DC2626',
    emoji: '🏇',
    status: 'working',
    currentTask: 'Revisando estratégia',
    lastTask: 'Planejamento Q1',
  },
  {
    id: 'aria',
    name: 'ARIA',
    role: 'Estrategista',
    color: '#7C3AED',
    emoji: '📊',
    status: 'working',
    currentTask: 'Análise de mercado',
    lastTask: 'Relatório semanal',
  },
  {
    id: 'nora',
    name: 'NORA',
    role: 'Roteirista',
    color: '#EC4899',
    emoji: '✍️',
    status: 'idle',
    lastTask: 'Roteiro ep. 12',
  },
  {
    id: 'vega',
    name: 'VEGA',
    role: 'Produção',
    color: '#F59E0B',
    emoji: '🎬',
    status: 'working',
    currentTask: 'Renderizando vídeo',
    lastTask: 'Edição final ep. 11',
  },
  {
    id: 'luna',
    name: 'LUNA',
    role: 'Publicação',
    color: '#3B82F6',
    emoji: '📱',
    status: 'idle',
    lastTask: 'Post TikTok agendado',
  },
  {
    id: 'atlas',
    name: 'ATLAS',
    role: 'Analytics',
    color: '#10B981',
    emoji: '📈',
    status: 'idle',
    lastTask: 'Dashboard atualizado',
  },
  {
    id: 'bob',
    name: 'Bob',
    role: 'Dev',
    color: '#6366F1',
    emoji: '🔨',
    status: 'idle',
    lastTask: 'Deploy v2.3',
  },
];
